import React, { useState, useEffect, useMemo } from "react";
import { useToast } from "@/components/ui/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { 
  Sparkles, 
  Send, 
  Trash2, 
  Edit3, 
  Eye, 
  RefreshCw, 
  CheckCircle2, 
  AlertCircle, 
  TrendingUp, 
  FileText, 
  Clock, 
  ExternalLink,
  ClipboardCheck,
  Wand2,
  Image as ImageIcon
} from "lucide-react";

import { BlockNoteEditor, PartialBlock } from "@blocknote/core";
import { BlockNoteView } from "@blocknote/mantine";
import "@blocknote/core/fonts/inter.css";
import "@blocknote/mantine/style.css";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { ADMIN_NAV_ITEMS } from "@/constants/adminNavItems";

const DRAFT_KEY = "postBlogDraft";
const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5001";

interface BlogItem {
  _id: string;
  title: string;
  slug: string;
  content: string;
  category: string;
  coverImage: string;
  bannerImage?: string;
  excerpt?: string;
  tags?: string[];
  status: "draft" | "published";
  seoScore?: number;
  seoAnalysis?: {
    titleScore: number;
    contentLengthScore: number;
    keywordDensityScore: number;
    readabilityScore: number;
    suggestions: string[];
  };
  isAutoGenerated?: boolean;
  generatedAt?: string;
  publishedAt?: string;
  createdAt: string;
}

const ensureBlockIds = (blocks: any[]): PartialBlock[] => {
  if (!Array.isArray(blocks)) return [];
  return blocks.map((block: any, idx: number) => ({
    ...block,
    id: block?.id || `block-${Date.now()}-${idx}-${Math.random().toString(36).substr(2, 6)}`,
    children: Array.isArray(block?.children) ? ensureBlockIds(block.children) : [],
  }));
};

// Smart Auto-Format Text Parser (Supports HTML Tags, Markdown, Slash Commands /h1, /h2, etc.)
const parseTextToBlockNote = (rawText: string): PartialBlock[] => {
  if (!rawText || !rawText.trim()) return [];

  const htmlBlocks: PartialBlock[] = [];

  // 1. Try DOMParser for HTML input (<h1>, <h2>, <p>, <ul>, <ol>, <table>, etc.)
  if (
    typeof window !== "undefined" &&
    (rawText.includes("<p") ||
      rawText.includes("<h1") ||
      rawText.includes("<h2") ||
      rawText.includes("<ul") ||
      rawText.includes("<ol") ||
      rawText.includes("<table"))
  ) {
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(rawText, "text/html");
      const children = Array.from(doc.body.children);

      if (children.length > 0) {
        children.forEach((el, idx) => {
          const blockId = `block-${Date.now()}-${idx}-${Math.random().toString(36).substr(2, 6)}`;
          const tagName = el.tagName.toLowerCase();
          const textContent = el.textContent || "";

          if (tagName === "h1") {
            htmlBlocks.push({
              id: blockId,
              type: "heading",
              props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 1 },
              content: [{ type: "text", text: textContent.trim(), styles: {} }],
            });
          } else if (tagName === "h2") {
            htmlBlocks.push({
              id: blockId,
              type: "heading",
              props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
              content: [{ type: "text", text: textContent.trim(), styles: {} }],
            });
          } else if (tagName === "h3" || tagName === "h4" || tagName === "h5" || tagName === "h6") {
            htmlBlocks.push({
              id: blockId,
              type: "heading",
              props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 3 },
              content: [{ type: "text", text: textContent.trim(), styles: {} }],
            });
          } else if (tagName === "ul") {
            const listItems = Array.from(el.querySelectorAll("li"));
            listItems.forEach((li, lIdx) => {
              htmlBlocks.push({
                id: `block-${Date.now()}-${idx}-${lIdx}-${Math.random().toString(36).substr(2, 6)}`,
                type: "bulletListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: li.textContent?.trim() || "", styles: {} }],
              });
            });
          } else if (tagName === "ol") {
            const listItems = Array.from(el.querySelectorAll("li"));
            listItems.forEach((li, lIdx) => {
              htmlBlocks.push({
                id: `block-${Date.now()}-${idx}-${lIdx}-${Math.random().toString(36).substr(2, 6)}`,
                type: "numberedListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: li.textContent?.trim() || "", styles: {} }],
              });
            });
          } else if (tagName === "table") {
            const rows = Array.from(el.querySelectorAll("tr"));
            rows.forEach((tr, rIdx) => {
              const cells = Array.from(tr.querySelectorAll("th, td")).map((c) => c.textContent?.trim() || "");
              if (cells.length > 0) {
                htmlBlocks.push({
                  id: `block-${Date.now()}-${idx}-${rIdx}-${Math.random().toString(36).substr(2, 6)}`,
                  type: "paragraph",
                  props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                  content: [{ type: "text", text: cells.join(" | "), styles: rIdx === 0 ? { bold: true } : {} }],
                });
              }
            });
          } else if (textContent.trim()) {
            htmlBlocks.push({
              id: blockId,
              type: "paragraph",
              props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
              content: [{ type: "text", text: textContent.trim(), styles: {} }],
            });
          }
        });

        if (htmlBlocks.length > 0) return htmlBlocks;
      }
    } catch (e) {
      console.error("DOMParser HTML parsing fallback to regex line parser", e);
    }
  }

  // 2. Line-by-line fallback parser for Plain Text, Slash Commands, and Markdown
  const lines = rawText.split("\n").map((l) => l.trim()).filter(Boolean);
  const blocks: PartialBlock[] = [];

  lines.forEach((line, idx) => {
    const blockId = `block-${Date.now()}-${idx}-${Math.random().toString(36).substr(2, 6)}`;

    // Slash commands /h1, /h2, /h3, /p, /bullet, /number, /quote, /faq
    if (/^\/h1[:\s]/i.test(line)) {
      const text = line.replace(/^\/h1[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "heading",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 1 },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\/h2[:\s]/i.test(line)) {
      const text = line.replace(/^\/h2[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "heading",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\/h3[:\s]/i.test(line)) {
      const text = line.replace(/^\/h3[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "heading",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 3 },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\/?(bullet\s*list|bulletlist|bullet_list|bullet|ul)[:\s]/i.test(line)) {
      const text = line.replace(/^\/?(bullet\s*list|bulletlist|bullet_list|bullet|ul)[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "bulletListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\/?(numbered\s*list|numberedlist|numbered_list|number|ol)[:\s]/i.test(line)) {
      const text = line.replace(/^\/?(numbered\s*list|numberedlist|numbered_list|number|ol)[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "numberedListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\/(p|paragraph)[:\s]/i.test(line)) {
      const text = line.replace(/^\/(p|paragraph)[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "paragraph",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\/faq[:\s]/i.test(line)) {
      const text = line.replace(/^\/faq[:\s]*/i, "");
      blocks.push({
        id: blockId,
        type: "heading",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 3 },
        content: [{ type: "text", text: `Q: ${text}`, styles: { bold: true } }],
      });
    }
    // Markdown syntax (# Heading, ## Subheading, ### H3)
    else if (line.startsWith("# ") || line.startsWith("## ") || line.startsWith("### ")) {
      const level = line.startsWith("# ") ? 1 : line.startsWith("## ") ? 2 : 3;
      const text = line.replace(/^#+\s*/, "");
      blocks.push({
        id: blockId,
        type: "heading",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: level as any },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (line.startsWith("- ") || line.startsWith("* ") || line.startsWith("• ")) {
      const text = line.replace(/^[-*•]\s*/, "");
      blocks.push({
        id: blockId,
        type: "bulletListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (/^\d+\.\s*/.test(line)) {
      const text = line.replace(/^\d+\.\s*/, "");
      blocks.push({
        id: blockId,
        type: "numberedListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text, styles: {} }],
      });
    } else if (line.endsWith("?") || (line.length < 80 && line === line.toUpperCase() && line.length > 5)) {
      blocks.push({
        id: blockId,
        type: "heading",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
        content: [{ type: "text", text: line, styles: {} }],
      });
    } else {
      blocks.push({
        id: blockId,
        type: "paragraph",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text: line, styles: {} }],
      });
    }
  });

  return blocks;
};

const ReadOnlyPreview = ({ content }: { content: string }) => {
  const previewEditor = useMemo(() => {
    let initialContent: PartialBlock[] | undefined;
    try {
      if (content && content !== "[]") {
        const parsed = JSON.parse(content);
        if (Array.isArray(parsed) && parsed.length > 0) {
          initialContent = ensureBlockIds(parsed);
        }
      }
    } catch (e) {
      console.error("Error parsing content for preview", e);
    }
    return BlockNoteEditor.create({ initialContent });
  }, [content]);

  return <BlockNoteView editor={previewEditor} editable={false} theme="light" />;
};

const extractExcerptFromBlocks = (blocks: any[]): string => {
  if (!Array.isArray(blocks) || blocks.length === 0) return "";
  let fullText = "";

  for (const block of blocks) {
    if (block.type === "paragraph" || block.type === "heading") {
      if (Array.isArray(block.content)) {
        const text = block.content.map((c: any) => c.text || "").join(" ").trim();
        if (text && !text.toLowerCase().startsWith("frequently asked") && !text.startsWith("Q:") && !text.startsWith("Q -")) {
          fullText += (fullText ? " " : "") + text;
        }
      }
    }
    if (fullText.length >= 160) break;
  }

  // Clean text and truncate nicely to 140-155 chars
  const cleaned = fullText.replace(/\s+/g, " ").trim();
  if (cleaned.length <= 155) return cleaned;

  const truncated = cleaned.slice(0, 150);
  const lastSpace = truncated.lastIndexOf(" ");
  return (lastSpace > 100 ? truncated.slice(0, lastSpace) : truncated) + "...";
};

const PostBlog = () => {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState<"drafts" | "editor" | "published">("drafts");
  const [loading, setLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [publishingId, setPublishingId] = useState<string | null>(null);

  const BLOGS_PER_PAGE = 9;
  const [drafts, setDrafts] = useState<BlogItem[]>([]);
  const [publishedBlogs, setPublishedBlogs] = useState<BlogItem[]>([]);
  const [publishedPage, setPublishedPage] = useState(1);
  const [draftsPage, setDraftsPage] = useState(1);
  const [editingBlogId, setEditingBlogId] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    title: "",
    category: "Coworking",
    excerpt: "",
    content: "[]",
    tags: "",
  });

  // Dual Image State
  const [coverImageFile, setCoverImageFile] = useState<File | null>(null);
  const [coverPreviewUrl, setCoverPreviewUrl] = useState<string | null>(null);
  const [bannerImageFile, setBannerImageFile] = useState<File | null>(null);
  const [bannerPreviewUrl, setBannerPreviewUrl] = useState<string | null>(null);

  // Quick Paste & Auto Format Modal
  const [showPasteModal, setShowPasteModal] = useState(false);
  const [pastedRawText, setPastedRawText] = useState("");

  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [selectedSeoModal, setSelectedSeoModal] = useState<BlogItem | null>(null);

  // Initialize BlockNote Editor safely
  const editor = useMemo(() => {
    let initialContent: PartialBlock[] | undefined;
    const savedDraft = localStorage.getItem(DRAFT_KEY);
    if (savedDraft) {
      try {
        const parsed = JSON.parse(savedDraft);
        if (parsed.content && parsed.content !== "[]") {
          const blocks = JSON.parse(parsed.content);
          if (Array.isArray(blocks) && blocks.length > 0) {
            initialContent = ensureBlockIds(blocks);
          }
        }
      } catch (e) {
        console.error("Error parsing draft content", e);
        localStorage.removeItem(DRAFT_KEY);
      }
    }

    try {
      return BlockNoteEditor.create({
        initialContent,
        uploadFile: async (file: File) => {
          try {
            const body = new FormData();
            body.append("file", file);
            const res = await fetch(`${API_BASE_URL}/api/blogs/editor-upload`, {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${getAuthToken()}`,
                "x-flashspace-csrf": "true",
              },
              credentials: "include",
              body,
            });

            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            const data = await res.json();
            return data.url || "";
          } catch (error: any) {
            console.error("Image upload failed:", error);
            toast({ title: "Upload Error", description: "Failed to upload image", variant: "destructive" });
            return "";
          }
        }
      });
    } catch (e) {
      console.error("BlockNoteEditor create failed, fallback to empty editor", e);
      localStorage.removeItem(DRAFT_KEY);
      return BlockNoteEditor.create();
    }
  }, []);

  const categories = ["Coworking", "Virtual Office", "Business Setup", "Office Space", "Enterprise", "Artificial Intelligence"];

  // Helper to extract JWT token from any stored key
  const getAuthToken = () => {
    return (
      localStorage.getItem("token") ||
      localStorage.getItem("accessToken") ||
      localStorage.getItem("adminToken") ||
      localStorage.getItem("flashspace_token") ||
      localStorage.getItem("auth_token") ||
      ""
    );
  };

  useEffect(() => {
    const mainContainers = document.querySelectorAll(".overflow-y-auto, main, #root");
    if (showPasteModal) {
      document.body.style.overflow = "hidden";
      document.documentElement.style.overflow = "hidden";
      mainContainers.forEach((el) => {
        (el as HTMLElement).style.overflow = "hidden";
      });
    } else {
      document.body.style.overflow = "";
      document.documentElement.style.overflow = "";
      mainContainers.forEach((el) => {
        (el as HTMLElement).style.overflow = "";
      });
    }
    return () => {
      document.body.style.overflow = "";
      document.documentElement.style.overflow = "";
      mainContainers.forEach((el) => {
        (el as HTMLElement).style.overflow = "";
      });
    };
  }, [showPasteModal]);

  // Fetch admin drafts and published blogs
  const fetchAdminBlogs = async () => {
    setLoading(true);
    try {
      const response = await fetch(`${API_BASE_URL}/api/blogs/admin/drafts`, {
        headers: {
          "Authorization": `Bearer ${getAuthToken()}`,
          "x-flashspace-csrf": "true",
        },
        credentials: "include",
      });
      const data = await response.json();
      if (data.success) {
        setDrafts(data.drafts || []);
        setPublishedBlogs(data.published || []);
      }
    } catch (err) {
      console.error("Failed to fetch admin blogs", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAdminBlogs();
  }, []);

  // Reset editor cleanly to 1 default block with unique id
  const resetEditorContent = () => {
    try {
      editor.replaceBlocks(editor.document, [
        {
          id: `block-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`,
          type: "paragraph",
          content: [],
        },
      ]);
    } catch (e) {
      console.error("Error resetting editor content", e);
    }
  };

  // Trigger manual 5 AI drafts generation
  const handleGenerateFiveDraftsNow = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch(`${API_BASE_URL}/api/blogs/admin/generate-now`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${getAuthToken()}`,
          "x-flashspace-csrf": "true",
        },
        credentials: "include",
      });
      const data = await res.json();
      if (data.success) {
        toast({
          title: "5 AI Drafts Generated! 🚀",
          description: "Fresh SEO-optimized blogs are ready for 1-click publishing.",
          variant: "default",
        });
        await fetchAdminBlogs();
        setActiveTab("drafts");
      } else {
        throw new Error(data.message || "Generation failed");
      }
    } catch (err: any) {
      toast({
        title: "Generation Error",
        description: err.message || "Failed to generate AI drafts",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  // Quick Paste & Auto-Format Converter handler
  const handleApplyQuickPaste = () => {
    if (!pastedRawText || !pastedRawText.trim()) {
      toast({ title: "Warning", description: "Please paste text into the box first.", variant: "destructive" });
      return;
    }

    const formattedBlocks = parseTextToBlockNote(pastedRawText);
    if (formattedBlocks.length > 0) {
      try {
        editor.replaceBlocks(editor.document, formattedBlocks);

        // Auto-fill excerpt form field immediately if empty
        if (!formData.excerpt.trim()) {
          const autoExcerpt = extractExcerptFromBlocks(formattedBlocks);
          if (autoExcerpt) {
            setFormData((prev) => ({ ...prev, excerpt: autoExcerpt }));
          }
        }

        toast({
          title: "Auto-Formatted Successfully! ✨",
          description: `Converted into ${formattedBlocks.length} clean headings, lists & paragraphs.`,
        });
        setShowPasteModal(false);
        setPastedRawText("");
      } catch (e) {
        console.error("Failed to inject formatted blocks", e);
        toast({ title: "Formatting Error", description: "Failed to load formatted content into editor.", variant: "destructive" });
      }
    }
  };

  // 1-Click Publish
  const handleOneClickPublish = async (blogId: string) => {
    setPublishingId(blogId);
    try {
      const res = await fetch(`${API_BASE_URL}/api/blogs/admin/publish/${blogId}`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${getAuthToken()}`,
          "x-flashspace-csrf": "true",
        },
        credentials: "include",
      });
      const data = await res.json();
      if (data.success) {
        toast({
          title: "Published Successfully! 🎉",
          description: "Blog is now live on your website.",
          variant: "default",
        });
        await fetchAdminBlogs();
      } else {
        throw new Error(data.message || "Publish failed");
      }
    } catch (err: any) {
      toast({
        title: "Publish Error",
        description: err.message || "Failed to publish blog",
        variant: "destructive",
      });
    } finally {
      setPublishingId(null);
    }
  };

  // Delete Blog
  const handleDeleteBlog = async (blogId: string) => {
    if (!window.confirm("Are you sure you want to delete this draft?")) return;
    try {
      const res = await fetch(`${API_BASE_URL}/api/blogs/admin/${blogId}`, {
        method: "DELETE",
        headers: {
          "Authorization": `Bearer ${getAuthToken()}`,
          "x-flashspace-csrf": "true",
        },
        credentials: "include",
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: "Deleted", description: "Draft blog removed." });
        await fetchAdminBlogs();
      }
    } catch (err) {
      toast({ title: "Error", description: "Failed to delete blog", variant: "destructive" });
    }
  };

  // Open blog in editor for fine-tuning
  const handleEditBlogInEditor = (blog: BlogItem) => {
    setEditingBlogId(blog._id);
    setFormData({
      title: blog.title,
      category: blog.category || "Coworking",
      excerpt: blog.excerpt || "",
      content: blog.content || "[]",
      tags: blog.tags ? blog.tags.join(", ") : "",
    });
    setCoverPreviewUrl(blog.coverImage || null);
    setBannerPreviewUrl(blog.bannerImage || blog.coverImage || null);

    try {
      if (blog.content && blog.content !== "[]") {
        const parsed = JSON.parse(blog.content);
        if (Array.isArray(parsed) && parsed.length > 0) {
          const safeBlocks = ensureBlockIds(parsed);
          editor.replaceBlocks(editor.document, safeBlocks);
        }
      }
    } catch (e) {
      console.error("Error setting editor blocks", e);
    }
    setActiveTab("editor");
  };

  const handleCoverFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setCoverImageFile(file);
      setCoverPreviewUrl(URL.createObjectURL(file));
    }
  };

  const handleBannerFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setBannerImageFile(file);
      setBannerPreviewUrl(URL.createObjectURL(file));
    }
  };

  const handleSubmitEditor = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const contentJson = JSON.stringify(editor.document);
      const computedExcerpt = formData.excerpt.trim() || extractExcerptFromBlocks(editor.document);

      const submitData = new FormData();
      submitData.append("title", formData.title);
      submitData.append("category", formData.category);
      submitData.append("excerpt", computedExcerpt);
      submitData.append("content", contentJson);

      const tagsArray = formData.tags.split(",").map(t => t.trim()).filter(Boolean);
      tagsArray.forEach(tag => submitData.append("tags[]", tag));
      submitData.append("tags", tagsArray.join(","));

      if (coverImageFile) {
        submitData.append("coverImage", coverImageFile);
      } else if (coverPreviewUrl) {
        submitData.append("coverImageUrl", coverPreviewUrl);
      } else {
        submitData.append("coverImageUrl", "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80");
      }

      if (bannerImageFile) {
        submitData.append("bannerImage", bannerImageFile);
      } else if (bannerPreviewUrl) {
        submitData.append("bannerImageUrl", bannerPreviewUrl);
      }

      let response;
      if (editingBlogId) {
        // Use FormData if file is being uploaded during update
        if (coverImageFile || bannerImageFile) {
          response = await fetch(`${API_BASE_URL}/api/blogs/admin/${editingBlogId}`, {
            method: "PUT",
            headers: {
              "Authorization": `Bearer ${getAuthToken()}`,
              "x-flashspace-csrf": "true",
            },
            credentials: "include",
            body: submitData,
          });
        } else {
          response = await fetch(`${API_BASE_URL}/api/blogs/admin/${editingBlogId}`, {
            method: "PUT",
            headers: {
              "Authorization": `Bearer ${getAuthToken()}`,
              "Content-Type": "application/json",
              "x-flashspace-csrf": "true",
            },
            credentials: "include",
            body: JSON.stringify({
              title: formData.title,
              category: formData.category,
              excerpt: computedExcerpt,
              content: contentJson,
              tags: tagsArray,
              coverImage: coverPreviewUrl,
              bannerImage: bannerPreviewUrl,
            }),
          });
        }
      } else {
        response = await fetch(`${API_BASE_URL}/api/blogs`, {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${getAuthToken()}`,
            "x-flashspace-csrf": "true",
          },
          credentials: "include",
          body: submitData,
        });
      }

      const data = await response.json();
      if (response.ok && data.success) {
        toast({ title: "Success", description: editingBlogId ? "Blog updated successfully!" : "Blog created & published!" });
        setFormData({ title: "", category: "Coworking", excerpt: "", content: "[]", tags: "" });
        resetEditorContent();
        setCoverImageFile(null);
        setCoverPreviewUrl(null);
        setBannerImageFile(null);
        setBannerPreviewUrl(null);
        setEditingBlogId(null);
        localStorage.removeItem(DRAFT_KEY);
        await fetchAdminBlogs();
        setActiveTab("published");
      } else {
        throw new Error(data.message || "Failed to save blog");
      }
    } catch (error: any) {
      toast({ title: "Error", description: error.message || "Failed to save blog", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const getSeoBadgeColor = (score: number = 85) => {
    if (score >= 90) return "bg-emerald-100 text-emerald-800 border-emerald-300";
    if (score >= 75) return "bg-amber-100 text-amber-800 border-amber-300";
    return "bg-rose-100 text-rose-800 border-rose-300";
  };

  return (
    <DashboardLayout
      portalName="FlashSpace Admin"
      portalDescription="Complete platform management"
      navItems={ADMIN_NAV_ITEMS}
    >
      <div className="p-4 sm:p-8 max-w-7xl mx-auto font-sans text-gray-900">
        
        {/* Top Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8 bg-white p-6 rounded-2xl border border-gray-200/80 shadow-sm">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Sparkles className="w-5 h-5 text-[#36503F]" />
              <h1 className="text-2xl font-bold text-gray-900">AI Blog Manager & Automation</h1>
            </div>
            <p className="text-sm text-gray-500">
              Daily 5 AI-generated blogs created at <strong>10:00 AM IST</strong> with SEO scoring & 1-Click Publishing.
            </p>
          </div>

          <Button
            onClick={handleGenerateFiveDraftsNow}
            disabled={isGenerating}
            className="bg-[#36503F] hover:bg-[#2c4133] text-[#FEF8CF] font-semibold px-5 py-2.5 rounded-xl shadow-sm flex items-center gap-2 transition-all shrink-0"
          >
            <RefreshCw className={`w-4 h-4 ${isGenerating ? "animate-spin" : ""}`} />
            {isGenerating ? "Generating 5 AI Drafts..." : "Generate 5 AI Drafts Now"}
          </Button>
        </div>

        {/* Tab Selector */}
        <div className="flex items-center gap-2 border-b border-gray-200 mb-8 overflow-x-auto">
          <button
            onClick={() => setActiveTab("drafts")}
            className={`pb-3.5 px-4 font-semibold text-sm transition-all relative flex items-center gap-2 shrink-0 ${
              activeTab === "drafts"
                ? "text-[#36503F] border-b-2 border-[#36503F]"
                : "text-gray-500 hover:text-gray-900"
            }`}
          >
            <Clock className="w-4 h-4" />
            Today's AI Drafts (10 AM Queue)
            {drafts.length > 0 && (
              <span className="bg-[#36503F] text-white text-[11px] font-bold px-2 py-0.5 rounded-full">
                {drafts.length}
              </span>
            )}
          </button>

          <button
            onClick={() => {
              setEditingBlogId(null);
              setFormData({ title: "", category: "Coworking", excerpt: "", content: "[]", tags: "" });
              resetEditorContent();
              setCoverPreviewUrl(null);
              setBannerPreviewUrl(null);
              setActiveTab("editor");
            }}
            className={`pb-3.5 px-4 font-semibold text-sm transition-all relative flex items-center gap-2 shrink-0 ${
              activeTab === "editor"
                ? "text-[#36503F] border-b-2 border-[#36503F]"
                : "text-gray-500 hover:text-gray-900"
            }`}
          >
            <Edit3 className="w-4 h-4" />
            {editingBlogId ? "Edit Blog in Editor" : "Create New Post"}
          </button>

          <button
            onClick={() => setActiveTab("published")}
            className={`pb-3.5 px-4 font-semibold text-sm transition-all relative flex items-center gap-2 shrink-0 ${
              activeTab === "published"
                ? "text-[#36503F] border-b-2 border-[#36503F]"
                : "text-gray-500 hover:text-gray-900"
            }`}
          >
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            Published Live Blogs ({publishedBlogs.length})
          </button>
        </div>

        {/* TAB 1: DAILY AI DRAFTS QUEUE */}
        {activeTab === "drafts" && (
          <div className="space-y-6">
            {loading ? (
              <div className="text-center py-12 bg-white rounded-2xl border border-gray-200">
                <RefreshCw className="w-8 h-8 animate-spin mx-auto text-[#36503F] mb-3" />
                <p className="text-sm font-medium text-gray-600">Loading daily AI draft blogs...</p>
              </div>
            ) : drafts.length === 0 ? (
              <div className="text-center py-16 bg-white rounded-2xl border border-dashed border-gray-300 p-8">
                <Sparkles className="w-12 h-12 text-[#36503F] mx-auto mb-4 opacity-80" />
                <h3 className="text-lg font-bold text-gray-900 mb-1">No AI Drafts in Queue</h3>
                <p className="text-sm text-gray-500 max-w-md mx-auto mb-6">
                  The automated 10:00 AM cron job runs daily. Click below to generate 5 fresh high-SEO drafts right now.
                </p>
                <Button
                  onClick={handleGenerateFiveDraftsNow}
                  disabled={isGenerating}
                  className="bg-[#36503F] text-[#FEF8CF] font-bold px-6 py-2.5 rounded-xl hover:bg-[#2c4133]"
                >
                  {isGenerating ? "Generating..." : "Generate 5 AI Drafts Now"}
                </Button>
              </div>
            ) : (
              <>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {drafts
                    .slice((draftsPage - 1) * BLOGS_PER_PAGE, draftsPage * BLOGS_PER_PAGE)
                    .map((blog) => (
                      <div
                        key={blog._id}
                        className="bg-white rounded-2xl border border-gray-200/80 shadow-sm overflow-hidden flex flex-col justify-between hover:shadow-md transition-shadow"
                      >
                        <div>
                          {/* Cover Image & Category */}
                          <div className="relative h-44 w-full bg-gray-100 overflow-hidden">
                            <img
                              src={blog.coverImage}
                              alt={blog.title}
                              className="w-full h-full object-cover"
                            />
                            <span className="absolute top-3 left-3 bg-black/80 text-white text-[11px] font-bold px-3 py-1 rounded-full uppercase tracking-wider shadow-sm">
                              {blog.category}
                            </span>

                            {/* SEO Score Badge */}
                            <div
                              onClick={() => setSelectedSeoModal(blog)}
                              className={`absolute top-3 right-3 border px-3 py-1 rounded-full text-xs font-bold shadow-sm bg-white/95 cursor-pointer hover:scale-105 transition-transform flex items-center gap-1.5 ${getSeoBadgeColor(
                                blog.seoScore
                              )}`}
                              title="Click to view SEO breakdown"
                            >
                              <TrendingUp className="w-3.5 h-3.5" />
                              SEO Score: {blog.seoScore || 85}/100
                            </div>
                          </div>

                          {/* Content */}
                          <div className="p-5">
                            <h3 className="font-bold text-gray-900 text-base leading-snug mb-2 line-clamp-2">
                              {blog.title}
                            </h3>
                            <p className="text-xs text-gray-500 line-clamp-3 mb-4">
                              {blog.excerpt}
                            </p>

                            {/* Tags */}
                            {blog.tags && blog.tags.length > 0 && (
                              <div className="flex flex-wrap gap-1.5 mb-4">
                                {blog.tags.slice(0, 3).map((tag) => (
                                  <span
                                    key={tag}
                                    className="text-[11px] bg-gray-100 text-gray-600 px-2 py-0.5 rounded-md font-medium"
                                  >
                                    #{tag}
                                  </span>
                                ))}
                              </div>
                            )}
                          </div>
                        </div>

                        {/* Bottom Actions */}
                        <div className="p-5 pt-0 border-t border-gray-100 flex items-center justify-between gap-2 mt-auto">
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handleEditBlogInEditor(blog)}
                              className="p-2 rounded-lg text-gray-600 hover:bg-gray-100 transition-colors"
                              title="Edit in Rich Text Editor"
                            >
                              <Edit3 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteBlog(blog._id)}
                              className="p-2 rounded-lg text-rose-600 hover:bg-rose-50 transition-colors"
                              title="Delete Draft"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>

                          <Button
                            onClick={() => handleOneClickPublish(blog._id)}
                            disabled={publishingId === blog._id}
                            className="bg-[#36503F] hover:bg-[#2c4133] text-[#FEF8CF] text-xs font-bold px-4 py-2.5 rounded-xl shadow-sm hover:shadow-md flex items-center gap-1.5 transition-all duration-200 cursor-pointer active:scale-95 border-0"
                          >
                            <Send className="w-3.5 h-3.5" />
                            {publishingId === blog._id ? "Publishing..." : "1-Click Publish"}
                          </Button>
                        </div>
                      </div>
                    ))}
                </div>

                {/* PAGINATION CONTROLS FOR DRAFTS */}
                {drafts.length > BLOGS_PER_PAGE && (
                  <div className="flex flex-col items-center justify-center gap-4 pt-6 border-t border-gray-200 bg-white p-5 rounded-2xl border border-gray-200/80 shadow-sm mt-6">
                    <span className="text-xs text-gray-500 font-semibold">
                      Showing {(draftsPage - 1) * BLOGS_PER_PAGE + 1} - {Math.min(draftsPage * BLOGS_PER_PAGE, drafts.length)} of {drafts.length} drafts
                    </span>

                    <div className="flex items-center gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        disabled={draftsPage === 1}
                        onClick={() => {
                          setDraftsPage((prev) => Math.max(prev - 1, 1));
                          window.scrollTo({ top: 0, behavior: "smooth" });
                        }}
                        className="text-xs font-bold px-3 py-1.5 h-9 rounded-xl"
                      >
                        Previous
                      </Button>

                      {Array.from({ length: Math.ceil(drafts.length / BLOGS_PER_PAGE) }, (_, i) => i + 1).map((pageNum) => (
                        <button
                          key={pageNum}
                          onClick={() => {
                            setDraftsPage(pageNum);
                            window.scrollTo({ top: 0, behavior: "smooth" });
                          }}
                          className={`w-9 h-9 rounded-xl text-xs font-bold transition-all ${
                            draftsPage === pageNum
                              ? "bg-[#36503F] text-[#FEF8CF] shadow-md"
                              : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                          }`}
                        >
                          {pageNum}
                        </button>
                      ))}

                      <Button
                        variant="outline"
                        size="sm"
                        disabled={draftsPage >= Math.ceil(drafts.length / BLOGS_PER_PAGE)}
                        onClick={() => {
                          setDraftsPage((prev) => Math.min(prev + 1, Math.ceil(drafts.length / BLOGS_PER_PAGE)));
                          window.scrollTo({ top: 0, behavior: "smooth" });
                        }}
                        className="text-xs font-bold px-3 py-1.5 h-9 rounded-xl"
                      >
                        Next
                      </Button>
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {/* TAB 2: RICH TEXT EDITOR & CREATION */}
        {activeTab === "editor" && (
          <form onSubmit={handleSubmitEditor} className="space-y-6 bg-white p-6 sm:p-8 rounded-2xl border border-gray-200/80 shadow-sm">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-gray-100">
              <div>
                <h2 className="text-lg font-bold text-gray-900">
                  {editingBlogId ? "Edit & Fine-Tune Blog" : "Create New Blog Post"}
                </h2>
                <p className="text-xs text-gray-500">
                  Use the BlockNote editor or click <span className="font-semibold text-[#36503F]">"Quick Paste & Auto-Format"</span> to convert raw text.
                </p>
              </div>

              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  onClick={() => setShowPasteModal(true)}
                  className="bg-[#334d3d] hover:bg-[#1a2d1d] text-[#FEF8C3] text-xs font-bold flex items-center gap-1.5 shadow-sm transition-all"
                >
                  <Wand2 className="w-4 h-4 text-[#FEF8C3]" /> Quick Paste & Auto-Format
                </Button>

                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setShowPreviewModal(true)}
                  className="flex items-center gap-2 text-xs font-semibold hover:bg-[#FEF8CF] transition-colors"
                >
                  <Eye className="w-4 h-4" /> Preview
                </Button>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="md:col-span-2 space-y-4">
                <div>
                  <label className="block text-xs font-bold uppercase text-gray-600 mb-1">Blog Title</label>
                  <Input
                    name="title"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    placeholder="Enter catchy SEO title (50-60 characters)..."
                    required
                    className="text-base font-semibold"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-bold uppercase text-gray-600 mb-1">Category</label>
                    <select
                      name="category"
                      value={formData.category}
                      onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                      className="w-full h-10 px-3 border border-input rounded-md text-sm font-medium focus:ring-1 focus:ring-ring"
                    >
                      {categories.map((c) => (
                        <option key={c} value={c}>{c}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase text-gray-600 mb-1">Tags (Comma separated)</label>
                    <Input
                      name="tags"
                      value={formData.tags}
                      onChange={(e) => setFormData({ ...formData, tags: e.target.value })}
                      placeholder="Virtual Office, Delhi, GST"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold uppercase text-gray-600 mb-1">Excerpt / Summary</label>
                  <Textarea
                    name="excerpt"
                    value={formData.excerpt}
                    onChange={(e) => setFormData({ ...formData, excerpt: e.target.value })}
                    placeholder="Short summary for Google search result snippet (120-160 characters)..."
                    rows={2}
                  />
                </div>
              </div>

              {/* DUAL IMAGE UPLOAD SECTION */}
              <div className="space-y-4">
                {/* 1. Small Card Cover Image */}
                <div>
                  <label className="block text-xs font-bold uppercase text-gray-600 mb-1 flex items-center justify-between">
                    <span>1. Card Cover Image</span>
                    <span className="text-[10px] text-gray-400 font-normal">Thumbnail for listing cards</span>
                  </label>
                  <div className="border-2 border-dashed border-gray-200 rounded-xl p-3 text-center h-36 flex flex-col justify-center items-center relative overflow-hidden bg-gray-50 hover:bg-gray-100 transition-colors">
                    {coverPreviewUrl ? (
                      <img src={coverPreviewUrl} alt="Card Cover Preview" className="w-full h-full object-cover absolute inset-0" />
                    ) : (
                      <div className="text-gray-400 text-xs font-medium">
                        <ImageIcon className="w-6 h-6 mx-auto mb-1 opacity-50" />
                        Upload Card Cover
                      </div>
                    )}
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleCoverFileChange}
                      className="absolute inset-0 opacity-0 cursor-pointer"
                    />
                  </div>
                </div>

                {/* 2. Full Article Banner Image */}
                <div>
                  <label className="block text-xs font-bold uppercase text-gray-600 mb-1 flex items-center justify-between">
                    <span>2. Article Header Banner</span>
                    <span className="text-[10px] text-gray-400 font-normal">Large banner on full blog page</span>
                  </label>
                  <div className="border-2 border-dashed border-gray-200 rounded-xl p-3 text-center h-36 flex flex-col justify-center items-center relative overflow-hidden bg-gray-50 hover:bg-gray-100 transition-colors">
                    {bannerPreviewUrl ? (
                      <img src={bannerPreviewUrl} alt="Banner Preview" className="w-full h-full object-cover absolute inset-0" />
                    ) : (
                      <div className="text-gray-400 text-xs font-medium">
                        <ImageIcon className="w-6 h-6 mx-auto mb-1 opacity-50" />
                        Upload Full Article Banner
                      </div>
                    )}
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleBannerFileChange}
                      className="absolute inset-0 opacity-0 cursor-pointer"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* BlockNote Rich Text Editor */}
            <div>
              <label className="block text-xs font-bold uppercase text-gray-600 mb-2">Content Editor</label>
              <div className="border border-gray-200 rounded-xl p-4 min-h-[400px] bg-white">
                <BlockNoteView editor={editor} theme="light" />
              </div>
            </div>

            <div 
              onClick={(e) => {
                const form = (e.currentTarget as HTMLElement).closest("form");
                if (form && !loading) {
                  form.requestSubmit();
                }
              }}
              className="pt-4 mt-6 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-4 bg-[#36503F]/5 hover:bg-[#36503F]/10 p-4 sm:p-5 rounded-2xl cursor-pointer transition-all duration-200 border border-[#36503F]/20 group shadow-sm"
            >
              <div className="flex items-center gap-2 text-xs font-bold text-[#36503F]">
                <Sparkles className="w-4 h-4 text-[#36503F]" />
                <span>Click anywhere inside this bar to publish your article immediately</span>
              </div>

              <Button 
                type="submit" 
                disabled={loading} 
                className="w-full sm:w-auto bg-[#36503F] group-hover:bg-[#2c4133] text-[#FEF8CF] font-bold px-8 py-3 rounded-xl shadow-md hover:shadow-lg transition-all duration-200 cursor-pointer active:scale-95 border-0 flex items-center justify-center gap-2 text-sm shrink-0"
              >
                <Send className="w-4 h-4" />
                {loading ? "Saving..." : editingBlogId ? "Update Blog" : "Publish Blog Now"}
              </Button>
            </div>
          </form>
        )}

        {/* TAB 3: PUBLISHED LIVE BLOGS */}
        {activeTab === "published" && (
          <div className="space-y-6">
            <div className="flex items-center justify-between bg-white p-6 rounded-2xl border border-gray-200/80 shadow-sm">
              <div>
                <h2 className="text-lg font-bold text-gray-900">Published Live Articles</h2>
                <p className="text-xs text-gray-500">
                  Live articles currently active on your website (Total: {publishedBlogs.length} | Page {publishedPage} of {Math.ceil(publishedBlogs.length / BLOGS_PER_PAGE) || 1})
                </p>
              </div>
            </div>

            {publishedBlogs.length === 0 ? (
              <div className="text-center py-16 bg-white rounded-2xl border border-dashed border-gray-300 p-8">
                <CheckCircle2 className="w-12 h-12 text-emerald-600 mx-auto mb-3" />
                <h3 className="text-lg font-bold text-gray-900 mb-1">No Published Blogs Yet</h3>
                <p className="text-sm text-gray-500 max-w-md mx-auto">
                  Published blogs will appear here in card view matching your main website layout.
                </p>
              </div>
            ) : (
              <>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {publishedBlogs
                    .slice((publishedPage - 1) * BLOGS_PER_PAGE, publishedPage * BLOGS_PER_PAGE)
                    .map((blog) => (
                      <div
                        key={blog._id}
                        className="bg-white rounded-2xl border border-gray-200/80 shadow-sm overflow-hidden flex flex-col justify-between hover:shadow-lg transition-all duration-300 group"
                      >
                        <div>
                          {/* Cover Image & Category */}
                          <div className="relative h-48 w-full bg-gray-100 overflow-hidden">
                            <img
                              src={blog.coverImage || "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80"}
                              alt={blog.title}
                              loading="lazy"
                              decoding="async"
                              className="w-full h-full object-cover transform group-hover:scale-105 transition-transform duration-500"
                            />
                            <span className="absolute top-3 left-3 bg-[#36503F] text-[#FEF8CF] text-[11px] font-bold px-3 py-1 rounded-full uppercase tracking-wider shadow-sm">
                              {blog.category}
                            </span>

                            <span className="absolute top-3 right-3 bg-black/75 text-white text-[11px] font-semibold px-2.5 py-1 rounded-full shadow-sm">
                              {new Date(blog.publishedAt || blog.createdAt).toLocaleDateString()}
                            </span>
                          </div>

                          {/* Content */}
                          <div className="p-5">
                            <h3 className="font-bold text-gray-900 text-base leading-snug mb-2 line-clamp-2 group-hover:text-[#36503F] transition-colors">
                              {blog.title}
                            </h3>
                            <p className="text-xs text-gray-500 line-clamp-3 mb-4">
                              {blog.excerpt || blog.content.substring(0, 150) + "..."}
                            </p>

                            {/* Tags */}
                            {blog.tags && blog.tags.length > 0 && (
                              <div className="flex flex-wrap gap-1.5 mb-2">
                                {blog.tags.slice(0, 3).map((tag) => (
                                  <span
                                    key={tag}
                                    className="text-[11px] bg-gray-100 text-gray-600 px-2 py-0.5 rounded-md font-medium"
                                  >
                                    #{tag}
                                  </span>
                                ))}
                              </div>
                            )}
                          </div>
                        </div>

                        {/* Bottom Actions */}
                        <div className="p-4 border-t border-gray-100 flex items-center justify-between gap-2 mt-auto bg-gray-50/50">
                          <div className="flex items-center gap-1.5">
                            <button
                              onClick={() => handleEditBlogInEditor(blog)}
                              className="p-2 rounded-lg text-gray-600 hover:bg-gray-200/80 transition-colors"
                              title="Edit in Editor"
                            >
                              <Edit3 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteBlog(blog._id)}
                              className="p-2 rounded-lg text-rose-600 hover:bg-rose-50 transition-colors"
                              title="Delete Live Blog"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>

                          <a
                            href={`/blogs/${blog.slug}`}
                            target="_blank"
                            rel="noreferrer"
                            className="bg-[#36503F] hover:bg-[#2c4133] text-[#FEF8CF] text-xs font-bold px-4 py-2 rounded-xl shadow-sm flex items-center gap-1.5 transition-all duration-200 hover:shadow-md active:scale-95"
                          >
                            <ExternalLink className="w-3.5 h-3.5" /> View Live Article
                          </a>
                        </div>
                      </div>
                    ))}
                </div>

                {/* PAGINATION CONTROLS FOR PUBLISHED BLOGS */}
                {publishedBlogs.length > BLOGS_PER_PAGE && (
                  <div className="flex flex-col items-center justify-center gap-4 pt-6 border-t border-gray-200 bg-white p-5 rounded-2xl border border-gray-200/80 shadow-sm mt-6">
                    <span className="text-xs text-gray-500 font-semibold">
                      Showing {(publishedPage - 1) * BLOGS_PER_PAGE + 1} - {Math.min(publishedPage * BLOGS_PER_PAGE, publishedBlogs.length)} of {publishedBlogs.length} articles
                    </span>

                    <div className="flex items-center gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        disabled={publishedPage === 1}
                        onClick={() => {
                          setPublishedPage((prev) => Math.max(prev - 1, 1));
                          window.scrollTo({ top: 0, behavior: "smooth" });
                        }}
                        className="text-xs font-bold px-3 py-1.5 h-9 rounded-xl"
                      >
                        Previous
                      </Button>

                      {Array.from({ length: Math.ceil(publishedBlogs.length / BLOGS_PER_PAGE) }, (_, i) => i + 1).map((pageNum) => (
                        <button
                          key={pageNum}
                          onClick={() => {
                            setPublishedPage(pageNum);
                            window.scrollTo({ top: 0, behavior: "smooth" });
                          }}
                          className={`w-9 h-9 rounded-xl text-xs font-bold transition-all ${
                            publishedPage === pageNum
                              ? "bg-[#36503F] text-[#FEF8CF] shadow-md"
                              : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                          }`}
                        >
                          {pageNum}
                        </button>
                      ))}

                      <Button
                        variant="outline"
                        size="sm"
                        disabled={publishedPage >= Math.ceil(publishedBlogs.length / BLOGS_PER_PAGE)}
                        onClick={() => {
                          setPublishedPage((prev) => Math.min(prev + 1, Math.ceil(publishedBlogs.length / BLOGS_PER_PAGE)));
                          window.scrollTo({ top: 0, behavior: "smooth" });
                        }}
                        className="text-xs font-bold px-3 py-1.5 h-9 rounded-xl"
                      >
                        Next
                      </Button>
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        )}

        {/* Quick Paste & Auto-Format Modal */}
        {showPasteModal && (
          <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-md flex items-center justify-center p-4 sm:p-6 overflow-hidden">
            <div className="bg-white rounded-2xl max-w-4xl w-full h-[82vh] flex flex-col p-6 sm:p-8 space-y-4 shadow-2xl border border-gray-100 relative overflow-hidden">
              <div className="flex justify-between items-center pb-3 border-b border-gray-100 flex-shrink-0">
                <h3 className="font-bold text-gray-900 text-lg flex items-center gap-2">
                  <Wand2 className="w-5 h-5 text-[#334d3d]" /> Quick Paste & Smart Auto-Formatter
                </h3>
                <button onClick={() => setShowPasteModal(false)} className="text-gray-400 hover:text-gray-600 font-bold text-lg">✕</button>
              </div>

              <p className="text-xs text-gray-500 flex-shrink-0">
                Paste raw text, Markdown (`#`, `##`, `-`), or Slash Commands (`/h1`, `/h2`, `/h3`, `/bullet`, `/number`, `/faq`). The engine will instantly format everything into rich blocks with IDs.
              </p>

              <div className="flex-1 min-h-0 w-full">
                <Textarea
                  value={pastedRawText}
                  onChange={(e) => setPastedRawText(e.target.value)}
                  placeholder={`Supported Formats Example:

/h1 Guide to Virtual Offices in Delhi
/h2 Key Benefits of Virtual Office Address
A virtual office address provides startups with a commercial presence for GST registration.

/bullet Cost savings up to 80%
/bullet Verified GST & MCA compliance
/bullet Dedicated mail forwarding

/faq Is Virtual Office Legal for GST Registration in Delhi?
Yes, under CGST rules, a virtual office address with valid NOC and Rent Agreement is 100% legal.

Or standard Markdown (# H1, ## H2, - Bullet, 1. Numbered)`}
                  className="w-full h-full min-h-[300px] font-mono text-xs border-gray-300 resize-none focus:ring-[#334d3d]"
                />
              </div>

              <div className="flex justify-end gap-3 pt-2 flex-shrink-0 border-t border-gray-100">
                <Button variant="outline" onClick={() => setShowPasteModal(false)} className="text-xs font-semibold hover:bg-[#FEF8CF] transition-colors">Cancel</Button>
                <Button onClick={handleApplyQuickPaste} className="bg-[#334d3d] hover:bg-[#1a2d1d] text-[#FEF8C3] hover:text-[#FEF8CF] font-bold text-xs flex items-center gap-2 transition-colors">
                  <ClipboardCheck className="w-4 h-4 text-[#FEF8C3] group-hover:text-[#FEF8CF]" /> Auto-Format & Load into Editor
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* SEO Breakdown Modal */}
        {selectedSeoModal && (
          <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="bg-white rounded-2xl max-w-md w-full p-6 space-y-4 shadow-xl border border-gray-200">
              <div className="flex justify-between items-center">
                <h3 className="font-bold text-gray-900 text-lg flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-[#36503F]" /> SEO Score Details
                </h3>
                <button onClick={() => setSelectedSeoModal(null)} className="text-gray-400 hover:text-gray-600">✕</button>
              </div>

              <div className="bg-gray-50 p-4 rounded-xl text-center">
                <div className="text-3xl font-black text-emerald-700">{selectedSeoModal.seoScore || 85}/100</div>
                <div className="text-xs font-bold text-gray-500 uppercase mt-1">Overall Search Ranking Score</div>
              </div>

              {selectedSeoModal.seoAnalysis?.suggestions && selectedSeoModal.seoAnalysis.suggestions.length > 0 && (
                <div>
                  <h4 className="text-xs font-bold text-gray-600 uppercase mb-2">Recommendations for Higher Ranking</h4>
                  <ul className="space-y-1.5 text-xs text-gray-700">
                    {selectedSeoModal.seoAnalysis.suggestions.map((sug, idx) => (
                      <li key={idx} className="flex items-start gap-1.5">
                        <AlertCircle className="w-3.5 h-3.5 text-amber-600 shrink-0 mt-0.5" />
                        <span>{sug}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <Button onClick={() => setSelectedSeoModal(null)} className="w-full bg-[#36503F] text-white">Close</Button>
            </div>
          </div>
        )}

        {/* Preview Modal */}
        {showPreviewModal && (
          <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="bg-white rounded-2xl max-w-3xl w-full max-h-[85vh] overflow-y-auto p-6 sm:p-8 relative">
              <button
                onClick={() => setShowPreviewModal(false)}
                className="absolute top-4 right-4 p-2 text-gray-400 hover:text-gray-600"
              >
                ✕
              </button>
              <h2 className="text-2xl font-bold mb-4">{formData.title || "Untitled Blog"}</h2>
              {(bannerPreviewUrl || coverPreviewUrl) && (
                <img src={bannerPreviewUrl || coverPreviewUrl || ""} alt="Cover" className="w-full h-64 object-cover rounded-xl mb-6" />
              )}
              <ReadOnlyPreview content={formData.content} />
            </div>
          </div>
        )}

      </div>
    </DashboardLayout>
  );
};

export default PostBlog;
